baseURL: "/"
title: M7moud
LanguageCode: en-US
pagination.pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: M7moud
  description: "This is a blog by Mahmoud Reda"
  keywords: [Blog, Portfolio, m7moudreda]
  author: "Mahmoud Reda"
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowWordCount: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  disableHLJS: true # to disable highlightjs
  disableShare: false
  disableHLJS: false
  searchHidden: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /images/logo_256.png
    favicon16x16: /images/logo_16.png
    favicon32x32: /images/logo_32.png
    apple_touch_icon: /images/logo_32.png
    safari_pinned_tab: /images/logo_32.png

  label:
    text: "Home"
    # icon: /images/logo_256.png
    # iconHeight: 25

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome!\U0001F44B"
    subtitle: "This website is a collection of my thoughts and learnings."
    imageUrl: "/images/profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: cover image
    # buttons:
    #   - name: Blog
    #     url: blog
    #   - name: Projects
    #     url: projects

  # home-info mode
  homeInfoParams:
    Title: "Welcome!\U0001F44B"
    Content: "This website is a collection of my thoughts and learnings."

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/m7moudredafouad"
    - name: github
      url: "https://github.com/m7moudredafouad"
    - name: youtube
      url: "https://youtube.com/@m7moudredafouad303"
    - name: x
      url: "https://x.com/m7moudredafouad"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

  # editPost:
  #   URL: "https://github.com/m7moudredafouad/m7moudredafouad.github.io/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: false # to append file path to Edit link

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5

pygmentsUseClasses: true
markup: # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monaki